### ISSUE TITLE
Appliance rental.

### ISSUE THREAD

**Issue by subhed** [ChicoState/PantryNode#1]
A good test of software design is how easy it can adapt to change. In this assignment, your team's job is to compare your current design and implementation to those needed to adopt new, extended requirements.
First, save your team's current UML diagram as it currently is, naming the file before.pdf or before.png
Second, go to your team's GitHub repository and create a new Issue: "Appliance rental." Note the issue number (#XXX).
Now, your job will be to update your UML diagram to reflect how it will address the new requirements. Save this updated version as after.pdf or after.png
For this assignment, submit both the before and after files (one submission per team). As you continue working on your project, implement this feature and any commits you make that are relevant to the new functionality, put the issue number in the commit. For example: "Add appliance class #1" or if you have a final commit that implements all of the new requirements, you can close the issue with the keyword "closes," such as "Adds appliance rental feature, closes #1"
New Requirements
The food pantry has acquired some kitchen appliances that can help students cook, such as pots, pans, cutting boards, and baking trays. The system should keep an inventory of these appliances as well as keep track of when students borrow any of the items. As an initial policy, the pantry plans to let students borrow any appliance for up to seven days. When they borrow an appliance, the system should indicate who borrowed it and when it is due to be returned. Once it has been returned, the system should show that it is available. However, since there are many of the same kind of appliance (e.g. large pan), the system should show how many pans are available to be borrowed and how many are currently "out" (being borrowed and not yet returned).

**Comment by subhed** [comment]
Appliance Rental Issue closed, Issue #1

**Comment by Jayesh-sathe** [comment]
Verified the document
