### ISSUE TITLE
Add Feed API Get Request - Home page

### ISSUE THREAD

**Issue by hardikpatil** [ChicoState/PantryNode#114]
Feed API Get Request

**Comment by briswells** [comment]
@hardikpatiljust to clarify the exact data you want. Are you looking for expired and soon to expire items, with field such as, name, expiration date, donation date, and quantity? Also what time period would you be looking for, I think it would be better to limit the duration returned on the back end vs returning all items and you doing the math on the front end.

**Comment by hardikpatil** [comment]
> @hardikpatil to clarify the exact data you want. Are you looking for expired and soon to expire items, with field such as, name, expiration date, donation date, and quantity? Also what time period would you be looking for, I think it would be better to limit the duration returned on the back end vs returning all items and you doing the math on the front end.

Yes, in the following format, 
`id: number; item: string;  expiry_date: string;  added_date: string;  quantity: number`
`{ id: 1, item: "Rice", expiry_date: "2023-08-12", quantity:1, added_date:"2023-04-25" }`

**Comment by AbhinavReddy-Dev** [comment]
@briswells @hardikpatil There is an expiry page that contains the information of the expired and expiring items information. I think the feed should be more of the recent activity of the pantry, like items added, donors added, items expired, etc. Please add to this idea.

**Comment by briswells** [comment]
> @briswells @hardikpatil There is an expiry page that contains the information of the expired and expiring items information. I think the feed should be more of the recent activity of the pantry, like items added, donors added, items expired, etc. Please add to this idea.

We 100% should eventually but I don't think we're there yet. I believe the idea of this is to recreate the old application dashboard feed using the new UI and database. That feed only dealt with expiring items as that was the only thing required by the specs. We could add this at a later time but adding to many features now could over complicate things when the app is in an unstable state.

**Comment by briswells** [comment]
@hardikpatil Just finished the code. I'm going to rebase with main soon. Should I open a PR into main or should I merge into a different branch?
