### ISSUE TITLE
Add linter to frontend

### ISSUE THREAD

**Issue by AbhinavReddy-Dev** [ChicoState/PantryNode#116]
There is a need to add a linter to the frontend to check for any warnings and errors. This linter is specific to react code.
_Anyone who wants to work on this can assign themselves, I will help setup of linter._

**Comment by AbhinavReddy-Dev** [comment]
_Originally posted by @AbhinavReddy-Dev in https://github.com/ChicoState/PantryNode/discussions/42#discussioncomment-5223163_

**Comment by Jooms** [comment]
Handled by 150
https://github.com/ChicoState/PantryNode/pull/150
