### ISSUE TITLE
Properly Set up login

### ISSUE THREAD

**Issue by Jooms** [ChicoState/PantryNode#118]
During MR #101 where the frontend and backend were being connected a couple of things were disabled in the login functionality.

1. Passwords are compared plain-text. (handled in #101)
2. The backend doesn't return any user information. (Needed)
3. The backend returns a redirect, the frontend doesn't care. (Task #120)

Reasoning:
1) Our dummy data inserts passwords as plain-text, not hashed. We need to enable the signup functionality to properly hash and salt the password. Then we need to update the login functionality properly bcrypt.compare. This also means the dummy test data in the database needs to be updated to hashed / salted passwords.
2) Ideally it would return something like session token, or at least a users's names to be shown on the dashboard. Right now it just redirects.
3) The frontend needs to figure out where the backend wants it to go (login or `/`), and redirect correctly. Right now it just ignores it.

FYI: @briswells and @prestonmasseyblake

**Comment by briswells** [comment]
@Jooms Why did you cut out the bvrypt compare? The passwords, minus the ones in the dummy data, were being stored and compared as salted hashes. When I wrote the dummy data it was before updating passport.js and I just haven't updated, but all new users created get hashed. The user_id was also already returning as part of the session cookie, and I believe a session token as well.

**Comment by Jooms** [comment]
Fair question.
I felt the top priority was to connect the Frontend to the Backend.  Secondary is setting up the login and sign up correctly. 
This let me test the connectivity, and was the smallest change I could come up with to satisfy my top priority, especially when that top priority is (at least by me) perceived to be a hard-blocker for the rest of the class.
With your explanation I don't believe it would be hard to re-add it appropriately but this was the amount of time I had.

In order to make sure it *does* get re-added, I created this (and #119) to track fast-follows that are needed after #101 goes it.
With 101 going in as-is, we can do things like:
* Spin off the Frontend teams to start connecting their pages to the backend apis that already exist
* Clean up the docker-compose.yml to deploy everything with the write vars (and validate it works for a fresh clone).
* Fix the login flow
* Set up the Sign up flow
*  and more.

**Comment by Jooms** [comment]
This task is now tracking the major task
 - [ ] The backend doesn't return any user information
 
A frontend and backend dev are needed for this

**Comment by briswells** [comment]
Removed redirects for [backend login route](https://github.com/ChicoState/PantryNode/pull/164). Now returns json data including user email. I kept the user data simple I as I unsure what was needed. Any backend routes will be able to pull all user information since we're using sessions. Frontend team will need to specify exactly what user information is needed.
