### ISSUE TITLE
Join DISCORD now!

### ISSUE THREAD

**Issue by AbhinavReddy-Dev** [ChicoState/PantryNode#151]
https://discord.gg/rVEPt9CK6D

**Comment by kbuffardi** [comment]
This isn't a proper software issue so I'm going to close this. However, thanks for sharing the discord.

**Comment by AbhinavReddy-Dev** [comment]
> This isn't a proper software issue so I'm going to close this. However, thanks for sharing the discord.

Yeah, I wanted everyone to see this for a couple days and then close it as most them don't know where to find the link to join. Thanks for closing it though! I was just looking to close it.
