### ISSUE TITLE
backend testing

### ISSUE THREAD

**Issue by briswells** [ChicoState/PantryNode#157]
Currently there is no testing for the backend. This will need to be implemented to comply with project requirements.

**Comment by briswells** [comment]
superagent can be used to help with authentication, but login route needs to be updated for it to work properly

**Comment by kbuffardi** [comment]
I agree that a lot more effort needs to go toward testing. However, I would rather dedicate testing to each feature and keep issues relatively small. Testing the whole backend is too broad of an issue so I am going to close this issue in favor of PR/Issues that are dedicated to particular features.
