### ISSUE TITLE
Containerize MVP

### ISSUE THREAD

**Issue by kbuffardi** [ChicoState/PantryNode#18]
- [ ] Use Docker to automate the build for the project, using the current dependencies and infrastructure
- [ ] Update the `README.md` to provide instructions on how to use the container(s)

**Comment by shubhamlatkar** [comment]
Containerization of pantry node using Dockerfile [Dockerfile](https://github.com/shubhamlatkar/PantryNode/blob/%2326-DeprecationWarning-and-mongoErrorContextSymbol/Dockerfile)

**Comment by AbhinavReddy-Dev** [comment]
I am reopening this issue until we get at least two approvals from the contributors to merge in development branch.

**Comment by briswells** [comment]
Can you please create a feature branch for this issue? As we all are working on this project tracking down a forked version on a single persons github doesn't seem efficient. Also don't forget the README needs to be updated. That's a side note though. Can you add a docker-compose for the main npm container? The DB migration ( #19 ) will be running on it's own container so we'll need docker-compose to run both.

**Comment by shubhamlatkar** [comment]
> Can you please create a feature branch for this issue? As we all are working on this project tracking down a forked version on a single persons github doesn't seem efficient. Also don't forget the README needs to be updated. That's a side note though. Can you add a docker-compose for the main npm container? The DB migration ( #23 ) will be running on it's own container so we'll need docker-compose to run both.

Hi @briswells, I think there is already [docker-container](https://github.com/ChicoState/PantryNode/tree/docker-container) branch created for containerisation and there is a [docker-compose](https://github.com/shubhamlatkar/PantryNode/blob/%2318-containerize-MVP/docker-compose.yml) which runs MongoDB and node container and can be modified to adapt to PostgreSQL.

**Comment by shubhamlatkar** [comment]
Hi @AbhinavReddy-Dev @sourabhk25 and @kbuffardi could we merge the docker-container branch to main and close the issue?

**Comment by Jooms** [comment]
Looks like !43 will handle a chunk of it by 
1. Creating a Dockerfile
2. Creating a docker-compose.yml that starts a mongodb and the server
3. Adding some content to the README for how to use it.

We still need
1. Someone to add a Dockerfile build step to the CI.
