### ISSUE TITLE
Linter vs Build Actions

### ISSUE THREAD

**Issue by briswells** [ChicoState/PantryNode#181]
I just noticed on my most recent PR that the linter action for frontend was passing but the build action was failing due to ESlint errors. I am unsure why these are using a different set of rules or why we have 2 actions both checking for linting.

**Comment by jayrevolinskyjr** [comment]
The [action workflow](https://github.com/ChicoState/PantryNode/actions/runs/4760422001/jobs/8460728583) in question.

Looks like it has to do with let vs. var, I will take a deeper look into why this is the case tomorrow. My current thought is that since this specific ESLint setting is set to an error and not a warn that it will fail to build but I am not sure exactly why.

**Comment by jayrevolinskyjr** [comment]
> The [action workflow](https://github.com/ChicoState/PantryNode/actions/runs/4760422001/jobs/8460728583) in question.

> Looks like it has to do with let vs. var.

I investigated further on the assumption that the frontend build is using react-scripts but I am not certain and will need someone to confirm my questions below. 
-
Does react-scripts use create-react-app? If not, how are we building the frontend? It looks like [many other people had this problem before](https://www.reddit.com/r/reactjs/comments/s1bchp/failed_to_compile_error_for_any_eslint_error_i/).

As a follow up on my investigation and the discussion with @Jooms @briswells @AbhinavReddy-Dev in discord, it seems that the react-scripts will toss a compilation error when the linter fails for the frontend, this is compounded by the linter setting the 'let vs. var' rule as a warning. 

There seems to be one of two ways to fix this bug:
1. We enable the 'let vs. var' rule as an error in the linter action to make the two actions cohesive.
      - This is a simple change for the current linter configuration but enforces a stricter standard, although replacing `var` with `let` is a simple change.
2. We set the ESLINT_NO_DEV_ERRORS=true in the .env file to override the linter tossing build compilation errors, as suggested [here](https://stackoverflow.com/questions/64518226/my-create-react-app-is-failing-to-compile-due-to-eslint-error).
      - This is likely to have unintended consequences since it will negate a portion of the workflow functionality.

Personally, I am leaning towards option 1, what are other's thoughts on this?

**Comment by AbhinavReddy-Dev** [comment]
> > The [action workflow](https://github.com/ChicoState/PantryNode/actions/runs/4760422001/jobs/8460728583) in question.
> 
> > Looks like it has to do with let vs. var.
> 
> ## I investigated further on the assumption that the frontend build is using react-scripts but I am not certain and will need someone to confirm my questions below.
> Does react-scripts use create-react-app? If not, how are we building the frontend? It looks like [many other people had this problem before](https://www.reddit.com/r/reactjs/comments/s1bchp/failed_to_compile_error_for_any_eslint_error_i/).
> 
> As a follow up on my investigation and the discussion with @Jooms @briswells @AbhinavReddy-Dev in discord, it seems that the react-scripts will toss a compilation error when the linter fails for the frontend, this is compounded by the linter setting the 'let vs. var' rule as a warning.
> 
> There seems to be two options to fix this bug:
> 
> 1. We enable the 'let vs. var' rule as an error in the linter action to make the two actions cohesive.
>    
>    * This is a simple change for the current linter configuration but enforces a stricter standard, although replacing `var` with `let` is also simple.
> 2. We set the ESLINT_NO_DEV_ERRORS=true in the .env file to override the linter tossing build compilation errors, as suggested [here](https://stackoverflow.com/questions/64518226/my-create-react-app-is-failing-to-compile-due-to-eslint-error).
>    
>    * This is likely to have unintended consequences since it will negate a portion of the workflow functionality.
> 
> Personally, I am leaning towards option 1, what are other's thoughts on this?

I agree with your position on this, we should go ahead replace the var to let or let to var as the linter suggests. This is the right way to keep the code quality in check for the future. EOD, the usage of var/ let depends on the certain things that block of code is trying to do.
