### ISSUE TITLE
Quagga scanner continues to use the camera.

### ISSUE THREAD

**Issue by AbhinavReddy-Dev** [ChicoState/PantryNode#184]
This is a trivial issue but, 

The scanner continues to use the camera even after the scan is stopped, and also when the user switches the page.
Expected behavior is to stop using the camera once the user stops it manually, and automatically when the user navigates to a different page.

**Comment by ysiddhapura** [comment]
> This is a trivial issue but,
> 
> The scanner continues to use the camera even after the scan is stopped, and also when the user switches the page. Expected behavior is to stop using the camera once the user stops it manually, and automatically when the user navigates to a different page.

We can work on this issue. Currently, there is an option to manually pause the camera in the address bar. But we can work on making it automated.

**Comment by AbhinavReddy-Dev** [comment]
Yes, I have closed it using address bar, but somehow the camera indicator on a MacOS device is still lit. This could be a MacOS only issue though.

> > This is a trivial issue but,
> > The scanner continues to use the camera even after the scan is stopped, and also when the user switches the page. Expected behavior is to stop using the camera once the user stops it manually, and automatically when the user navigates to a different page.
> 
> We can work on this issue. Currently, there is an option to manually pause the camera in the address bar. But we can work on making it automated.

**Comment by ysiddhapura** [comment]
> Yes, I have closed it using address bar, but somehow the camera indicator on a MacOS device is still lit. This could be a MacOS only issue though.
> 
> > > This is a trivial issue but,
> > > The scanner continues to use the camera even after the scan is stopped, and also when the user switches the page. Expected behavior is to stop using the camera once the user stops it manually, and automatically when the user navigates to a different page.
> > 
> > 
> > We can work on this issue. Currently, there is an option to manually pause the camera in the address bar. But we can work on making it automated.

Okay sounds good, will look into this.

**Comment by ysiddhapura** [comment]
Fixed the issue: Added a state variable cameraOn to keep track of whether the camera is on or off. Also modified the useEffect hook to start or stop the camera based on the value of cameraOn. When the user clicks the "stop" button, it will update the cameraOn state to false which triggers the useEffect hook to stop the camera.

Please check https://github.com/ChicoState/PantryNode/pull/187 @AbhinavReddy-Dev @Anoushka444
