### ISSUE TITLE
Add testing scaffold

### ISSUE THREAD

**Issue by kbuffardi** [ChicoState/PantryNode#21]
- [x] Add infrastructure for automated testing, with emphasis on unit testing and acceptance testing
- [x] Incorporate testing into DevOps instrumentation
- [x] Add CI workflow to run all tests for PR and for `main` branch
- [x] Add coverage report for all pulls to `main` along with a status badge in `README.md`

**Comment by rohitkarhadkar** [comment]
I have set up the Jest testing framework and added a unit test case to verify the existence of a user in the database. Can you please review the code, so that we can proceed with writing additional test cases for other files as well? 
[https://github.com/ChicoState/PantryNode/tree/unitTest](url)

**Comment by sourabhk25** [comment]
> I have set up the Jest testing framework and added a unit test case to verify the existence of a user in the database. Can you please review the code, so that we can proceed with writing additional test cases for other files as well? [https://github.com/ChicoState/PantryNode/tree/unitTest](url)


The code looks good to me. @rohitkarhadkar, you can raise the PR for getting reviews from other reviewers as well.
I executed the code and test case passed on my local machine - 

<img width="643" alt="authSignUp_test_review" src="https://user-images.githubusercontent.com/22402315/224623070-498dca2f-c641-4d59-a9d8-7b066ac65754.png">


Below are some suggestions - 
1. We should rename 'auth.js' as 'authSignupController.js' / 'authSignup.js' because there is already one more file as 'auth.js' in the config folder and we might need to create a test case for login authentication as well.
2. Similarly, we should modify the name of 'auth.test.js' to 'authSignupController.test.js' for better clarity.
3. Also, we should add one or two lines about the execution of test cases using Docker container/ local config using ‘npm test’.

**Comment by AbhinavReddy-Dev** [comment]
@rohitkarhadkar can you please create a feature branch for this as 'backend-testing' and push the code to it so we can run it locally and then approve for merging into main? I see that @sourabhk25 was able to run it successfully, if the changes are already present in a branch that is accessible to all, then please let us know the branch name.

**Comment by rohitkarhadkar** [comment]
> @rohitkarhadkar can you please create a feature branch for this as 'backend-testing' and push the code to it so we can run it locally and then approve for merging into main? I see that @sourabhk25 was able to run it successfully, if the changes are already present in a branch that is accessible to all, then please let us know the branch name.

Here is the link to branch [unitTest](https://github.com/ChicoState/PantryNode/tree/unitTest)

**Comment by AbhinavReddy-Dev** [comment]
> > @rohitkarhadkar can you please create a feature branch for this as 'backend-testing' and push the code to it so we can run it locally and then approve for merging into main? I see that @sourabhk25 was able to run it successfully, if the changes are already present in a branch that is accessible to all, then please let us know the branch name.
> 
> Here is the link to branch [unitTest](https://github.com/ChicoState/PantryNode/tree/unitTest)

It worked for me, we can merge it now or after we make changes with appropriate naming convention.

**Comment by rohitkarhadkar** [comment]
Hi guys, I have raised a [Pull Request](https://github.com/ChicoState/PantryNode/pull/59). Could you please review the code and confirm the application workflow is in order before merging into main?

**Comment by rohitkarhadkar** [comment]
> > > @rohitkarhadkar can you please create a feature branch for this as 'backend-testing' and push the code to it so we can run it locally and then approve for merging into main? I see that @sourabhk25 was able to run it successfully, if the changes are already present in a branch that is accessible to all, then please let us know the branch name.
> > 
> > 
> > Here is the link to branch [unitTest](https://github.com/ChicoState/PantryNode/tree/unitTest)
> 
> It worked for me, we can merge it now or after we make changes with appropriate naming convention.

I have done the naming conventions suggested by @sourabhk25 in latest commit. Could we merge after testing the application workflow?

**Comment by AbhinavReddy-Dev** [comment]
> > > > @rohitkarhadkar can you please create a feature branch for this as 'backend-testing' and push the code to it so we can run it locally and then approve for merging into main? I see that @sourabhk25 was able to run it successfully, if the changes are already present in a branch that is accessible to all, then please let us know the branch name.
> > > 
> > > 
> > > Here is the link to branch [unitTest](https://github.com/ChicoState/PantryNode/tree/unitTest)
> > 
> > 
> > It worked for me, we can merge it now or after we make changes with appropriate naming convention.
> 
> I have done the naming conventions suggested by @sourabhk25 in latest commit. Could we merge after testing the application workflow?

Sure! But I'd suggest doing it now if it doesn't affect the current flow. If it does then we'd have to make changes too.

**Comment by rohitkarhadkar** [comment]
Sure, As soon as the review is approved we can push to main.

**Comment by briswells** [comment]
Looks like my most recent merge into main broke the tests as we now use different models for the new database.  I'm thinking we should update this so the test hits the route in it's current state, then we create a new issue for separating out routes and controllers.

**Comment by kbuffardi** [comment]
Keep in mind everyone that this issue is only setting up the infrastructure so that we can run tests. This issue isn't actually testing the production code. In fact, we don't need to test the *current* production code because most of it will dramatically change due to the infrastructure changes.

In addition to setting up Jest, and incorporating it into the DevOps (explained in the checklist above), it should just have a **smoke test** to just confirm that the project can build and tests run (running only a smoke test) and report the desired results. That's it.

Once we have that in place, we can merge the testing infrastructure into `main` and testing production code can be incorporated into other (and new) issues (since contributing guidelines requires unit tests to accompany changes to production code).

**Comment by rohitkarhadkar** [comment]
Hi guys, we have written 2 smoke test cases with jest setup. @sourabhk25, @AbhinavReddy-Dev, @chetan2298, please review the code so that we can merge to main.
[testing_scaffold](https://github.com/ChicoState/PantryNode/pull/75)

**Comment by nvkulkarni12** [comment]
Hello Team,

Can we have a call apart from the class meeting. Probably on Friday or any other day if possible. We can divide the tasks between us and set goals for each sprint. And then we can work over on them over the weekends. 

Any other ideas than this are more than welcome. Please suggest.

**Comment by TanviMahajan11** [comment]
> Hello Team,
> 
> Can we have a call apart from the class meeting. Probably on Friday or any other day if possible. We can divide the tasks between us and set goals for each sprint. And then we can work over on them over the weekends.
> 
> Any other ideas than this are more than welcome. Please suggest.

Sure, Friday works for me too. It would be really good if we discuss and divide the tasks.

**Comment by nvkulkarni12** [comment]
> > Hello Team,
> > Can we have a call apart from the class meeting. Probably on Friday or any other day if possible. We can divide the tasks between us and set goals for each sprint. And then we can work over on them over the weekends.
> > Any other ideas than this are more than welcome. Please suggest.
> 
> Sure, Friday works for me too. It would be really good if we discuss and divide the tasks.

Great. Could you suggest the time if possible. I am free after 10 AM PST on Fridays. Please suggest. We can set a recurring meeting on Zoom and meet.

**Comment by nvkulkarni12** [comment]
https://csuchico-my.sharepoint.com/:x:/g/personal/nvkulkarni_csuchico_edu/Ednixoti5jBHs8RMpYxR_dYBT7X7u3uQTsBBFXRdOiGdLQ?e=8p5aMx

Hello, Attached is the link to excel sheet to collaborate and write Test cases as discussed during scrum today. Please feel free to add more columns to the template. I am thinking to write the test cases related to each page in a separate sheet for better maintenance.

**Comment by kbuffardi** [comment]
@nvkulkarni12 thanks for taking initiative on the testing efforts. A couple things:

1. This Issue is simply setting up the infrastructure, not actually writing tests (beyond the smoke test)
2. I don't mind if you all use other documents to help organize, but all defects found should be logged here on GitHub as an **Issue**

Also to everyone involved -- we seem to be *most* of the way through this issue, but the third and fourth specification from my description is still missing. These should be tackled and merged into main before we make any PRs with tests.

**Comment by DevangRaval1** [comment]
As discussed in Scrum @nvkulkarni12 and I will be working on the CI workflow

**Comment by sourabhk25** [comment]
As discussed in Scrum, @G1411 and I will be working on the Coverage report part.

**Comment by sourabhk25** [comment]
Coverage report and badge added
PR - https://github.com/ChicoState/PantryNode/pull/179
