### ISSUE TITLE
Testing donar.js frontend

### ISSUE THREAD

**Issue by kushalramakanth** [ChicoState/PantryNode#210]
- [ ] 100% coverage

**Comment by kushalramakanth** [comment]
@hardikpatil I opened this issue to do the testing for donar page but closed it since it was already done by someone else. So I'm closing this issue.

**Comment by hardikpatil** [comment]
> @hardikpatil I opened this issue to do the testing for donar page but closed it since it was already done by someone else without creating an issue. So I'm closing this issue.

No worries, if its done, should be marked `closed` , I had reopened it since this issue was no reference to it or any discussion of it any pr.
