### ISSUE TITLE
Update UI dependencies

### ISSUE THREAD

**Issue by kbuffardi** [ChicoState/PantryNode#24]
- [ ] Replace for Bootstrap with modern, flexible UI framework
- [ ] Remove all Chico State-specific branding for broad "PantryNode"

**Comment by AbhinavReddy-Dev** [comment]
I was thinking we can use [TailwindCSS](https://tailwindcss.com/docs/installation) for the UI Framework, its a responsive mobile first class based framework.

**Comment by decoles** [comment]
Pull request made for:
- [*] Remove all Chico State-specific branding for broad "PantryNode"

**Comment by AbhinavReddy-Dev** [comment]
Maybe we can close this issue as we will replace Bootstrap for Tailwind CSS and will not include any Chico State branding or references while migrating to React.

**Comment by decoles** [comment]
> Maybe we can close this issue as we will replace Bootstrap for Tailwind CSS and will not include any Chico State branding or references while migrating to React.

I agree, will close this issue if its alright with everyone.

**Comment by prasannarajezzzy** [comment]
> > Maybe we can close this issue as we will replace Bootstrap with Tailwind CSS and will not include any Chico State branding or references while migrating to React.
> 
> I agree, will close this issue if it's alright with everyone.
tailwind regarding changes done like configuration if not it is still an issue?

**Comment by KishoreMenda** [comment]
@Gajjela-Koushik-Reddy was in discussions
