### ISSUE TITLE
DeprecationWarning & mongoErrorContextSymbol errors when starting project on Mac

### ISSUE THREAD

**Issue by ysiddhapura** [ChicoState/PantryNode#26]
After entering the command 'npm start'
Getting these errors: 
 -DeprecationWarning: current Server Discovery and Monitoring engine is deprecated
 -connection error MongoNetworkError: failed to connect to server [cluster0-shard-00-02-fy0po.mongodb.net:27017] on first    connect [MongoNetworkError: connection 10 to cluster0-shard-00-02-fy0po.mongodb.net:27017 closed
- [Symbol(mongoErrorContextSymbol)]: {}
Any debugging help with this issue would be appreciated.

**Comment by hardikpatil** [comment]
same [
![Screenshot 2023-02-26 at 17 52 04](https://user-images.githubusercontent.com/12888989/221453858-9f8cc764-2aa7-4ffc-8d9e-4413bb0966e6.png)
](url)

**Comment by kbuffardi** [comment]
Note: quoting error messages as text is preferable since it is searchable, opposed to images.

That said, Google turned up some potential fixes. Start your exploration here and let us know of your updates: https://stackoverflow.com/questions/57895175/server-discovery-and-monitoring-engine-is-deprecated/57899638#57899638

**Comment by ysiddhapura** [comment]
By adding **'useUnifiedTopology: true'** to -> mongoose.connect(db, { useNewUrlParser: true, useUnifiedTopology: true }); in the files:  **app.js, sale.js** and **users.js** **resolved** the initial **DeprecationWarning and the initial MongoNetworkError.** 

Now able to load the home page. 

**mongoErrorContextSymbol error** still persists, when navigating to the Register/Sign In pages. 
The server closes with a 
-connection error MongooseError [MongooseServerSelectionError]: connection <monitor> to 52.54.19.162:27017 closed |  
            reason: TopologyDescription 
             type: 'ReplicaSetNoPrimary',
             error: MongoNetworkError: connection <monitor> to 52.54.19.162:27017 closed
             [Symbol(mongoErrorContextSymbol)]

**Comment by abhilashSreenivasa** [comment]
> same [ ![Screenshot 2023-02-26 at 17 52 04](https://user-images.githubusercontent.com/12888989/221453858-9f8cc764-2aa7-4ffc-8d9e-4413bb0966e6.png) ](url)

Getting the same error.
