### ISSUE TITLE
Create Feature Branches for Each Issue

### ISSUE THREAD

**Issue by AbhinavReddy-Dev** [ChicoState/PantryNode#31]
Looks like we are all making pull requests to main branch, hence felt like there is a need to create feature branches in the main repo for us to be able to make pull requests to respective branch before merging that branch into main. 
Please make any necessary recommendations.

**Comment by AbhinavReddy-Dev** [comment]
Closing this after the discussion in class.

**Comment by Jooms** [comment]
Some related discussion
https://github.com/ChicoState/PantryNode/discussions/38
