### ISSUE TITLE
Create Documentation Of Dependencies For Frontend Update Readme.md with how to start and dependencies

### ISSUE THREAD

**Issue by prestonmasseyblake** [ChicoState/PantryNode#67]

**Comment by KishoreMenda** [comment]
Hey guys!
What is the plan to start on documenting the dependencies?

**Comment by MSS-Shalavritha** [comment]
We have to update the technology stack that we are are currently using.

**Comment by arshiya19** [comment]
Im not understanding what to do particularly, can you be more specific.

**Comment by abhinaydruva** [comment]
First we will update technology satck then we will write documentation on all dependencies.

**Comment by shmansa** [comment]
We have to also update the readme in PantryNodeReact

**Comment by TJSidhu1** [comment]
We need to align with the frontend team to get more details about the technologies used. Right now, we know of React and TypeScript.

**Comment by arshiya19** [comment]
@Gajjela-Koushik-Reddy 
Okay

**Comment by prestonmasseyblake** [comment]
I have a pull request for this currently. Check it out and review it when you can.
