### ISSUE TITLE
React UI - Routing and State Management

### ISSUE THREAD

**Issue by AbhinavReddy-Dev** [ChicoState/PantryNode#72]
I will work on setting up the Routing and State Management for the UI, so that we can start the functional implementation.
- [x] Routing
- [x] State Management

**Comment by AbhinavReddy-Dev** [comment]
I need suggestions for state management, I am currently thinking of implementing Redux, given our future scalability potential. Can you please recommend some alternates to Redux and how they are better than Redux for the current use case? @xl26 @sathyanarayanan-v @prestonmasseyblake @prasannarajezzzy

**Comment by xl26** [comment]
> I need suggestions for state management, I am currently thinking of implementing Redux, given our future scalability potential. Can you please recommend some alternates to Redux and how they are better than Redux for the current use case? @xl26 @sathyanarayanan-v @prestonmasseyblake @prasannarajezzzy 

There are quite a few options we could explore like RxJs which is pretty popular. But for ease of use and community wise redux state management is a good way to move forward. But let's keep the options open for now and explore a bit on rxjs.

**Comment by sathyanarayanan-v** [comment]
I am okay with redux slice to manage the state. React query is also an option to manage states which natively provide data caching and debouncing.

**Comment by AbhinavReddy-Dev** [comment]
After carefully going through the documentation and various discussions on RxJS and Redux, I found that RxJS and Redux are totally two different things but they both do converge at a concept of observing the state from a distance.
Redux seems to be a more appropriate choice in this repo and it will be easier to understand to any novice given its folder structure.  I will try to implement and have an example page (won't interrupt the current flow) with all the functions that we might use for demonstration purpose and can be removed once all the pages are completely functional.
