### ISSUE TITLE
Feed Section on Home View

### ISSUE THREAD

**Issue by hardikpatil** [ChicoState/PantryNode#76]
-  Feed section on the home page. Ref - [Figma](https://www.figma.com/file/Ioe4ZC15X3NFJMSZPHeuPr/Pantry-Node-team-library?node-id=0%3A1&t=dMdc904te8ua7wlM-1)
- Stock quantity

**Comment by hardikpatil** [comment]
At the current stage, feeds display all the stock data in chronological order, should we render expired stocks as well or just those items expiring soon?

**Comment by hardikpatil** [comment]
> At the current stage, feed section display all the stock data(expired and expiring as well) in chronological order, should we render expired stocks as well or just those items expiring soon? or expiring on left section and expired on right section? something like that?

resolved. For now, separated both expired and expiring soon items on right-left section.

**Comment by AbhinavReddy-Dev** [comment]
> At the current stage, feed section display all the stock data(expired and expiring as well) in chronological order, should we render expired stocks as well or just those items expiring soon? or expiring on left section and expired on right section? something like that?
I'm thinking that feed will have everything that is recent, expiring items, expired items and recently added items. We need to contact the backend to properly understand what data can the api provide.
