### ISSUE TITLE
Create add donor along with donor table view page

### ISSUE THREAD

**Issue by murthy-001** [ChicoState/PantryNode#77]
We are covering the creation of the "donor page" and "donor added table" pages mentioned in Figma.

Tasks:
- [x] Donar Table List and Add Donar Form #105
- [ ] Validation on Add Donar Form and Redirect on Donate button click

**Comment by AbhinavReddy-Dev** [comment]
Please let me know if you need any help with understanding the components styling and implementation for this project so that the pull request review is not extensive and hopefully don't need another revision. I can hop on to a zoom call to give you both an idea of what structure and pattern is mostly followed.

**Comment by abhilashSreenivasa** [comment]
@AbhinavReddy-Dev Do you think it's a good idea to create a coding standard document that explains the styling rules that we are following, Folder structure, and stuff?  Probably avoids the problem that you just mentioned.

**Comment by AbhinavReddy-Dev** [comment]
> @AbhinavReddy-Dev Do you think it's a good idea to create a coding standard document that explains the styling rules that we are following, Folder structure, and stuff? Probably avoids the problem that you just mentioned.

That's a great idea indeed, there is something called [Material Design](https://m3.material.io/components) to help understand the styling and also there is this [Storybook](https://storybook.js.org/docs/react/get-started/why-storybook) for documenting the components for the application, if you're interested we both can look into it to add it to the project for better component documentation.

**Comment by murthy-001** [comment]
> @AbhinavReddy-Dev Do you think it's a good idea to create a coding standard document that explains the styling rules that we are following, Folder structure, and stuff? Probably avoids the problem that you just mentioned.

Having a standardized approach to these aspects of software development can help improve consistency and maintainability across the project, as well as make it easier for new contributors like me to understand the codebase and quickly get up to speed. 

Is the document already available? If so, could you please share a copy with me? I'd like to review it to ensure that I'm following the agreed-upon guidelines for code styling and folder structure.

If the document isn't available yet, I'd be happy to contribute to its creation or offer suggestions on what topics or guidelines we should include.

**Comment by murthy-001** [comment]
> Please let me know if you need any help with understanding the components styling and implementation for this project so that the pull request review is not extensive and hopefully don't need another revision. I can hop on to a zoom call to give you both an idea of what structure and pattern is mostly followed.

Thank you for your offer to help with understanding the components styling and implementation for the project. I'm currently working on the task and I appreciate the support.

Once I've finished the current task, I may need your help to review my implementation and ensure that it adheres to the styling guidelines. Would it be okay to reach out to you at that point for assistance? I'll be sure to keep you updated on my progress in the meantime.

**Comment by AbhinavReddy-Dev** [comment]
> > Please let me know if you need any help with understanding the components styling and implementation for this project so that the pull request review is not extensive and hopefully don't need another revision. I can hop on to a zoom call to give you both an idea of what structure and pattern is mostly followed.
> 
> Thank you for your offer to help with understanding the components styling and implementation for the project. I'm currently working on the task and I appreciate the support.
> 
> Once I've finished the current task, I may need your help to review my implementation and ensure that it adheres to the styling guidelines. Would it be okay to reach out to you at that point for assistance? I'll be sure to keep you updated on my progress in the meantime.

Sure, please create a feature branch _frontend_feature_ and push code to it, I'll run it and let you know if there are any changes that need be made.
