### ISSUE TITLE
Implement Sales Report (Dynamic)

### ISSUE THREAD

**Issue by briswells** [ChicoState/PantryNode#82]
The current sales report page just shows some hard coded categories which link to nothing. This is part of the original project requirements. I'm guessing it'll be easier to just start from the ground up designing this report.

**Comment by hardikpatil** [comment]
Does the current model include a category image field?

**Comment by AbhinavReddy-Dev** [comment]
So, we need to have a discussion on what data should be generated to send to the frontend to viz.
