### ISSUE TITLE
Form Validation 

### ISSUE THREAD

**Issue by prestonmasseyblake** [ChicoState/PantryNode#89]
-  Add validation for email, password, and phone number
- As per docs/[Foodbank ER Diagram.png](https://github.com/ChicoState/PantryNode/blob/main/docs/Foodbank%20ER%20Diagram.png) schema , in the sign-up View, add more field `First Name`, `Last Name` replacing `Name` field

Tasks:
- [x] Login page
- [x] Registration Sign-Up page

**Comment by hardikpatil** [comment]
Tasks:
- [ ] Login page
- [ ] Registration Sign-Up page
