### ISSUE TITLE
Stock Summary Page - Adding tables and Charts. 

### ISSUE THREAD

**Issue by abhilashSreenivasa** [ChicoState/PantryNode#91]
In this issue, We will be creating summary tables and generate charts using chartJS.

**Comment by abhilashSreenivasa** [comment]
I am working on the charts for summary page. If any one of you can start working on the tables, That would be great. I asked the backend team to provide more  details on the ReportType interface and the classes that are implementing them. Waiting for their reply.

**Comment by decoles** [comment]
Have a new branch created for summary page, tables are started.

**Comment by abhilashSreenivasa** [comment]
<img width="1440" alt="Screen Shot 2023-04-11 at 11 05 00 PM" src="https://user-images.githubusercontent.com/59731282/231366268-babc5dc5-2e69-4492-989c-2cf88ffedf12.png">
I was testing out different charts. Which one do you think we should go for?

**Comment by abhilashSreenivasa** [comment]
Hey @decoles, 
I was thinking of creating a toggle button at the top of the summary page that can switch back between chart and table. I think it is a good idea to separate tables and charts, Otherwise, it just looks clumsy. If you are working on anything on summary_page right now,  I don't want to push something and cause conflict.  Anyway, What do you think about the toggle? If you're cool with it, I'll get started on it.

**Comment by decoles** [comment]
@abhilashSreenivasa That sounds like a great idea! It does look really odd and doesn't flow well with the bar chart below the raw data. Disregard my most recent change just now saw this, oops.

**Comment by abhilashSreenivasa** [comment]
I made the changes and separated the tables and chart. Let me know what you think.  I'll add the comments as well. But I think this is as much as we can do without the backend data.

**Comment by decoles** [comment]
Toggle looks great, cant progress without backend data so will do pull request with what we have and update figma.

**Comment by abhilashSreenivasa** [comment]
> Toggle looks great, cant progress without backend data so will do pull request with what we have and update figma.

Great!I haven't checked if there were any build problems ,Other than that. I think we are good to go .

**Comment by abhilashSreenivasa** [comment]
Seems like we got some conflict in package.json. Were we supposed to merge 'frontend' branch before creating a pr?
