### ISSUE TITLE
Construct Register Success Page 

### ISSUE THREAD

**Issue by hardikpatil** [ChicoState/PantryNode#95]
Success page after new registration and login button to redirect as per design [Figma](https://www.figma.com/file/Ioe4ZC15X3NFJMSZPHeuPr/Pantry-Node-team-library?node-id=0%3A1&t=dMdc904te8ua7wlM-1)

**Comment by AbhinavReddy-Dev** [comment]
We have the UI freedom to make it efficient, so instead of creating a new page, we can show them an alert saying the registration successful and navigate them to home-page of the website.
